workflows:
  version: 2
  commit:
    jobs:
      - test
      - deploy:
          # Only run a deploy if tests pass and a new version tag has been pushed
          requires:
            - test
          filters:
            tags:
              only: /v[0-9]+(\.[0-9]+)*/
            branches:
              ignore: /.*/
jobs:
  test:
    docker:
      - image: circleci/node:7.10
    working_directory: ~/repo
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      # Install dependecies
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      # Run tests!
      - run: npm test -- --tap
  deploy:
    docker:
      - image: circleci/node:7.10
    working_directory: ~/repo
    steps:
      # Reads the npm publish key from the environment and confirgures the .npmrc file
      - run: echo "//registry.npmjs.org/:_authToken=$NPM_PUBLISH_KEY" >> ~/.npmrc
      - run: npm publish
