workflows:
  version: 2
  commit:
    jobs:
      - test:
      - deploy:
          requires: test
          # Only run a deploy if a new version tag has been pushed
          filters:
            tags:
              only: /v[0-9]+(\.[0-9]+)*/
            branches:
              ignore: /.*/
jobs:
  test:
    docker:
      - image: circleci/node:7.10
    working_directory: ~/repo
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      # Install dependecies
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      # Run tests!
      - run:
          name: Jest Suite
          command: npm test -- --ci --testResultsProcessor="jest-junit"
          environment:
            JEST_JUNIT_OUTPUT: "reports/junit/js-test-results.xml"
      - store_test_results:
          path: reports/junit/js-test-results.xml
      - persist_to_workspace:
          paths:
            - .
  deploy:
    docker:
      - image: circleci/node:7.10
    working_directory: ~/repo
    steps:
      # Reads the npm publish key from the environment and confirgures the .npmrc file
      - run: echo "//registry.npmjs.org/:_authToken=$NPM_PUBLISH_KEY" >> ~/.npmrc
      - run: npm publish
      # Since we have published a new version of the package, bump the docs too
      - add_ssh_keys:
          fingerprints:
            - "6b:f2:45:ac:be:96:f5:3d:76:d3:98:d0:7f:2c:8c:64"
      - run: git config --global user.email "$GH_EMAIL"
      - run: git config --global user.name "$GH_NAME"
      - run: npm run docs
